version: "3"

services:
    php-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8089:80"
        volumes:
            - ./:/var/www/html
        restart: always
